title: Voeg beweging toe aan een speler met een Character Controller
hero_image: images/banner.png
description: Voeg beweging toe aan een speler met een Character Controller
version: 4
listed: false
copyedit: false
last_tested: "2021-11-04"
steps:
  - 
    title: Voeg beweging toe aan een speler met een Character Controller
