title: Add Player movement with a Character Controller
hero_image: images/banner.png
description: Add Player movement with a Character Controller
version: 4
listed: false
copyedit: false
last_tested: "2021-11-04"
steps:
  - 
    title: Add Player movement with a Character Controller
