---
title: Ajouter un mouvement à un joueur avec un Character Controller
hero_image: images/banner.png
description: Ajouter un mouvement à un joueur avec un Character Controller
version: 4
listed: false
copyedit: false
last_tested: "2021-11-04"
steps:
  - title: Ajouter un mouvement à un joueur avec un Character Controller
